[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
rustflags = [
	# LLD (shipped with the Rust toolchain) is used as the default linker
	"-C", "link-arg=-Tlink.x",

	# if you run into problems with LLD switch to the GNU linker by commenting out
	# this line
	# "-C", "linker=riscv64-unknown-elf-ld",

	# if you need to link to pre-compiled C libraries provided by a C toolchain
	# use GCC as the linker by commenting out both lines above and then
	# uncommenting the three lines below
	# "-C", "linker=riscv64-unknown-elf-gcc",
	# "-C", "link-arg=-Wl,-Tlink.x",
	# "-C", "link-arg=-nostartfiles",
]